### ISSUE TITLE
Extract Logs from REST does not query logs from federated machines

### ISSUE THREAD

**Issue by JayaswalVaibhav** [Esri/Utility-Data-Management-Support-Tools#12]
We have a typical setup of ArcGIS Enterprise base deployment on one machine and a separate federated Server machine to host UN services. When I open the tool, it only displays the hosting server in the list of machines. It does not show the federated server site in the list of machines.
I am logged in as a user with administrator role in Pro.
When I leave the option to select machines unchecked, I expected the tool to include all machines in the output logs. However, I only see the hosting server logs in the output mobile geodatabase.
Am I missing something? How can I use this tool to extract logs from the federated server which hosts the UN services?

**Comment by pLeBlanc93** [comment]
@JayaswalVaibhav this should resolve the machine filtering.
[UtilityDataManagementSupport.zip](https://github.com/Esri/Utility-Data-Management-Support-Tools/files/8118572/UtilityDataManagementSupport.zip)

Delete your existing toolbox and use this.

**Comment by pLeBlanc93** [comment]
@JayaswalVaibhav
Your deployment -- is it two sites with a single machine each or is it one site with two machines?

I've not seen the results from query logs missing the `hasMore` key. What version of ArcGIS Server are you using?

**Comment by pLeBlanc93** [comment]
Perfect! That explains what is happening now. Depending on the machine(s) selected, I need to change which site I query logs from.

I'll stand up a multi site deployment and do some testing. Thanks a bunch!

**Comment by JayaswalVaibhav** [comment]
@pLeBlanc93 Thank you so much for sharing the RC. It appears to be working fine now. We will do some more testing and get back to you if we run into any issues.

**Comment by JayaswalVaibhav** [comment]
@pLeBlanc93 Thank you so much. The tool works like a charm.
