### ISSUE TITLE
Build Starting Points Tool - Input Utility Network - "Error in Parsing Arguments for Describe"

### ISSUE THREAD

**Issue by AubreyRhea** [Esri/Utility-Data-Management-Support-Tools#20]
**Describe the bug**
In the 5-2-2022 Release Build Starting Points Tool, when I select an Input Utility Network, I get an ERROR 032659: Error in Parsing Arguments for Describe. Strangely, I can make the error go away by selecting a Trace Results Class. But when I run the tool, I get a TypeError: 'NoneType' object is not subscriptable.

**To Reproduce**
1. Open the Build Starting Points tool
2. Browse to an Input Utility Network or paste a URL into the text box
3. A red X appears, hover over it to see the error
4. Scroll down to the New Trace Result Box, browse to an existing geodatabase, and type the name of a new layer
5. The red X goes away
6. Fill out the rest of the required fields and run the tool
7. Tool fails with NoneType error in the result messages

**Expected behavior**
I expect to be able to select a Utility Network that is in my project from the drop down box, and have it populate the Trace Configuration Name box with the configurations that exist in the Utility Network, as it has done in the previous 2-4-2022 release I was using. Then I expect to be able to run the tool and create a new point feature class.

**Screenshots**
![image](https://user-images.githubusercontent.com/7266277/172254725-d4d53e01-23e1-464a-a191-7a234a2309fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Utility Network version 5
 - ArcGIS Pro version 2.9

**Comment by MikeMillerGIS** [comment]
this should be fixed in https://github.com/Esri/Utility-Data-Management-Support-Tools/compare/versionDot9 can you verify?

**Comment by AubreyRhea** [comment]
Yes, that error is fixed, but now I am getting a new one:

Traceback (most recent call last):
File "<string>", line 30, in <module>
File "C:\python\Batch_Trace\UtilityDataManagementSupport.atbx\udms\esri.py", line 111, in wrapper
 File "C:\python\Batch_Trace\UtilityDataManagementSupport.atbx\udms\logic\__init__.py", line 170, in build_starting_points
File "C:\python\Batch_Trace\UtilityDataManagementSupport.atbx\udms\logic\trace.py", line 1387, in main
AttributeError: 'BuildStartingPoints' object has no attribute 'workspace'

**Comment by MikeMillerGIS** [comment]
Nice find, resolved that issue.  Tested against services, should be all fixed now

**Comment by AubreyRhea** [comment]
It is working without any errors now, thank you! The latest update is really great. I love how the starting points are a spatial layer now.
