### ISSUE TITLE
Error with Summarize Utility Network Errors

### ISSUE THREAD

**Issue by vertigork** [Esri/Utility-Data-Management-Support-Tools#21]
**Describe the bug**
I have certain datasets that throw an error when attempting to summarize the errors. I can reproduce on 2.9 and later versions of pro (along with the corresponding toolboxes.

**To Reproduce**
1. Download one of the misbehaving datasets
2. Run the tool
3. Experience the following error
  File "C:\Code\Utility-Data-Management-Support-Tools 3.1\UtilityDataManagementSupport.atbx#SummarizeUNErrors_udms.py", line 13, in <module>
  File "C:\Code\Utility-Data-Management-Support-Tools 3.1\UtilityDataManagementSupport.atbx\udms\esri.py", line 221, in wrapper
  File "C:\Code\Utility-Data-Management-Support-Tools 3.1\UtilityDataManagementSupport.atbx\udms\logic\__init__.py", line 465, in summarize_errors
  File "C:\Code\Utility-Data-Management-Support-Tools 3.1\UtilityDataManagementSupport.atbx\udms\logic\errors.py", line 499, in main
  File "C:\Code\Utility-Data-Management-Support-Tools 3.1\UtilityDataManagementSupport.atbx\udms\logic\errors.py", line 465, in gather_errors
  File "C:\ArcGIS\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\frame.py", line 684, in __init__
    data = list(data)
  File "C:\Code\Utility-Data-Management-Support-Tools 3.1\UtilityDataManagementSupport.atbx\udms\logic\errors.py", line 253, in read_errors
  File "C:\Code\Utility-Data-Management-Support-Tools 3.1\UtilityDataManagementSupport.atbx\udms\logic\errors.py", line 216, in extract_error_message
ValueError: invalid literal for int() with base 10: ' Additional rule violations exist.9'

**Expected behavior**
The tool should be able to handle all errors

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser N/a
 - Version 2.9 and later

**Smartphone (please complete the following information):**
n/a

**Additional context**
Datasets will be provided upon request, they use the utility network foundation datasets with particular errors.

**Comment by vertigork** [comment]
logged in error

**Comment by natdude** [comment]
I am having a similar error from this tool: "ValueError: invalid literal for int() with base 10: 'RuleID(s) 10783'"
Is there any type of workaround for this?

**Comment by pLeBlanc93** [comment]
[UtilityDataManagementSupport.zip](https://github.com/Esri/Utility-Data-Management-Support-Tools/files/9268995/UtilityDataManagementSupport.zip)

Can you give this a try? This fix will be picked up in the next release.

**Comment by natdude** [comment]
Thank you for the quick reply. I gave the new .zip a try, but I received a similar error for a differernt rule - "ValueError: invalid literal for int() with base 10: 'RuleID(s) 6363'"

**Comment by pLeBlanc93** [comment]
Interesting, this sounds a bit different than the original issue. Could you export your dirty area table to a new feature class and post here?

**Comment by natdude** [comment]
Unfortunately I cannot share the data due to a restriction on the data being used.

**Comment by pLeBlanc93** [comment]
If you can share a CSV of just the `ErrorCode` and `ErrorMessage` field values, I can debug from that. No geometry or other identifiable information will be there,

**Comment by natdude** [comment]
After discussing with my team, that would be acceptable, but would prefer an email to pass along the table. Additionally/alternatively, we do have a ticket open with ESRI, which the data has been shared (dirty areas are available), which could be another way to access the full data. 
Could you provide your email and I will pass along the data + ticket?

**Comment by pLeBlanc93** [comment]
Oh yeah, the support issue would be perfect.

Email is pleblanc at esri dot com

**Comment by pLeBlanc93** [comment]
[UtilityDataManagementSupport.zip](https://github.com/Esri/Utility-Data-Management-Support-Tools/files/9295017/UtilityDataManagementSupport.zip)
Alright, can you give this a try @natdude ?

The bug was specific to error 9 with multiple rules. If all is good on your end, this will be picked up in the next 2.9/3.0 releases.

**Comment by natdude** [comment]
Thank you again for help with this - the error 9 issue seems to have been resolved. However, this time we ran into "KeyError: 'multipoint'
Could this be caused by something that is unexpected in the data?

**Comment by MikeMillerGIS** [comment]
I searched the code base and do not see that used anywhere.  Can you post the full stack trace/error message?

**Comment by natdude** [comment]
![SummarizeUNErrors_Message](https://user-images.githubusercontent.com/110673253/184359320-0c92f8df-55f1-4ab1-940b-74c71e867438.png)

**Comment by MikeMillerGIS** [comment]
Thanks, that helped narrow down the issue.  We are still unsure how we are getting multipoints, but this fix should overcome the error and handle multipoint when encountered. 
[UtilityDataManagementSupport.zip](https://github.com/Esri/Utility-Data-Management-Support-Tools/files/9328535/UtilityDataManagementSupport.zip)

**Comment by natdude** [comment]
It worked for us now, thank you!
