### ISSUE TITLE
Enhancement request for the GP Tool:  Trace to Trace Configuration

### ISSUE THREAD

**Issue by mhirschheimer** [Esri/Utility-Data-Management-Support-Tools#25]
Enhancement request for the GP Tool:  Trace to Trace Configuration

**Describe the solution you'd like**
Please add optional input fields for: 
1) Description 
2) Tags

**Additional context**
After creating the trace configuration, I go to the REST endpoint, /traceConfigurations/alter, to set the Description value.  
Creating a new trace configuration with the proper attributes would be simpler if these fields are added to the GP Tool.

**Comment by MikeMillerGIS** [comment]
added
![image](https://user-images.githubusercontent.com/2707285/222829723-b847e8cf-bb85-454a-9b28-7e8fe1b5374a.png)
