### ISSUE TITLE
Trace to Trace Configuration:  The help on the "create trace configuration" option is confusing

### ISSUE THREAD

**Issue by mhirschheimer** [Esri/Utility-Data-Management-Support-Tools#26]
**Describe the bug**
Trace to Trace Configuration:  the help on the "create trace configuration" option is confusing

**Expected behavior**
The "Unchecked" value currently says, Do Nothing.
A more meaningful message is needed.  Something like:  The Trace Configuration won't be added to the database but a python script of the trace parameters will be created for you to review.

**Screenshots**

![TracetoTraceConfiguraiton](https://user-images.githubusercontent.com/63792289/186768239-798ec8f8-7cd4-451e-a717-3081605cc9ee.PNG)

**Comment by MikeMillerGIS** [comment]
This interface has been redesigned
