### ISSUE TITLE
Configure UN Layers does nothing

### ISSUE THREAD

**Issue by areynolds15** [Esri/Utility-Data-Management-Support-Tools#27]
When I run thee Configure UN layers tool, it does not do anything. It says it succeeds, but not changes are made to my pop-ups. 

Are there any prerequisites I should be aware of? For example, that I should be using a feature service in my map or that I need to use (or not use) subtype groups? I've closed and re-opened Pro, I've tried maps with subtype groups and without.

I'm using ArcGIS Pro 2.9.2 with UN version 5 in a file geodatabase.

**Comment by MikeMillerGIS** [comment]
It was designed for Subtype Group layers.  What does your TOC look like?

**Comment by areynolds15** [comment]
![TOC](https://user-images.githubusercontent.com/114671267/193045668-5cca0c0b-1949-4371-8bd2-d30300e48957.PNG)
TOC Image attached. I also have the Network object in the map. 

I'm running the tool with just the "Rule Popup" parameter checked. And I had a typo before, I am using Pro 2.9.1

**Comment by areynolds15** [comment]
Ah, I'm sorry. I needed to scroll down further in the pop-up. I apologize for wasting your time. It is working perfectly.

**Comment by MikeMillerGIS** [comment]
Nice, glad it is working!
