### ISSUE TITLE
"Select By Assotiation" tool return no selection

### ISSUE THREAD

**Issue by speleolontra** [Esri/Utility-Data-Management-Support-Tools#28]
Hi,
I've a problem with no solution: if I select a cable via Pro interface and I navigate on Attributes pane, I see 24 strand fiber contained.
When I use "Select by Association" tool to select strand fiber, it return no selection.

![immagine](https://user-images.githubusercontent.com/10747617/199034173-3cc4695f-a797-4cd1-822d-20f92a3b64a9.png)

It happens only for a specific Cable. I suspect that this problem is due to error on "Communication Junction Edge" #31 but I'don't found instructions to resolve error #31.

![immagine](https://user-images.githubusercontent.com/10747617/199035368-87e7f5d2-175a-4d50-bdbd-603f4df00dc1.png)

Where I'm Wrong? Ho to resolve this errors?
I' using different database (SQL Server and File geodatabase sources).

Thanks in advance.

**Comment by pLeBlanc93** [comment]
Select by Association can't select those records because the association records are pointing to records that don't exist. I'm not sure how the tree view is showing 24 of them.

If you load the Distribution Cable into modify associations, how many content records are there?

**Comment by speleolontra** [comment]
Hi @pLeBlanc93 , thanks for your support.
I see correctly 24 strands
![immagine](https://user-images.githubusercontent.com/10747617/199343563-526f1fbe-0c37-4a7a-b30b-c011205807f4.png)

Note that this problem with other cable assetid doesn't happen.
In my opinion, strands exists, but for an unknown reason select by assosciation tool failed to select.
Any suggestion is appreciated.

**Comment by MikeMillerGIS** [comment]
Can you expand the contains section in the attribute dialog?  Also, if you hover over the purplish box in the Modify Associations dialog, what does the mouse over text say?

**Comment by speleolontra** [comment]
Hi @MikeMillerGIS ,
here requested screenshots:
![immagine](https://user-images.githubusercontent.com/10747617/199836358-68a733b5-6159-4432-a73d-2750a5f60def.png)

If the purplish box is this:
![immagine](https://user-images.githubusercontent.com/10747617/199837745-afda76f9-931b-4848-b91e-802587b7b936.png)
no text appear on mouseover, but if I change Cable...
![immagine](https://user-images.githubusercontent.com/10747617/199838569-3b4ec7e5-cd27-4326-8ab2-83feaac7fc10.png)
I see no color for the box...
It seems that Pro wants to tell me anythings wrong...

**Comment by speleolontra** [comment]
on 25 cables drawed, it seems that 2 other than SM1161 have box coloured in Purple...
![immagine](https://user-images.githubusercontent.com/10747617/199840571-6b4030f4-d5c4-431c-8e65-895ad300ada5.png)

![immagine](https://user-images.githubusercontent.com/10747617/199841054-01b097f6-8a2d-4179-b2b0-d4b274298849.png)
But I have also Cable with no strands inside... How is it possible?
What's best strategy to correct in your opinion?
I hope this is useful for other people.
Thanks...

**Comment by MikeMillerGIS** [comment]
Anyway you can send us the gdb.  I need to see it to tell what is going on.  ***@***.***

**Comment by MikeMillerGIS** [comment]
Mmiller @ Esri .com

**Comment by MikeMillerGIS** [comment]
To close the issue, we identified this was caused but the association field being out of sync(bug in 2.9.5 and before).  If you modify an association of the feature it will reset the status and the tool will work.  

The tool uses the association status field to prefilter data as a performance optimization.  We are evaluating removing this optimization.
