### ISSUE TITLE
Add Utility Network System Tables: Tables not added to map

### ISSUE THREAD

**Issue by vertigork** [Esri/Utility-Data-Management-Support-Tools#3]
**Describe the bug**
When the tool is run with the "add outputs to map" option unchecked in a user's environment profile the layers are not added to the map.

**To Reproduce**
1. Go to Project > Options > Geoprocessing and uncheck "Add output datasets to an open map"
2. Click ok
3. Open a new map
4. Open the Add Utility Network System Tables tool
5. Select a Utility Network (in my environment it was hosted in a FGDB)
6. Selecta all the tables
7. Run the tool
8. The tool completes without warnings or errors, but no tables are added to the map
9. I see that there are 4 table views created in the file geodatabase

**Expected behavior**
All four tables should be added o the map with the supplied names

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: N/A
 - Version: ArcGIS Pro 2.9.0

**Additional context**
Performed against a standalone Utility Network in a file geodatabase.

**Comment by pLeBlanc93** [comment]
That's by design. 

When `Add output datasets to an open map` is unchecked, then the results from GP tools are not added to the active map. Most (all?) GP tools honor this setting.

**Comment by vertigork** [comment]
Because this tool is relying on that functionality to add the layer to the map it would make sense that either the tool would temporarily set that environment variable to be true then reset it once the layers had been added, or use another mechanism to add the layers to the map.

**Comment by MikeMillerGIS** [comment]
as designed
