### ISSUE TITLE
Capability to clone asset type in Asset Package

### ISSUE THREAD

**Issue by jalsup** [Esri/Utility-Data-Management-Support-Tools#31]
**Is your feature request related to a problem? Please describe.**
Capability to clone asset type in Asset Package.  

**Describe the solution you'd like**
The user would select an Asset Type in the Asset Package and duplicate it using a new name and the system would generate a new asset type code.  Tool would give an option to copy rules, Categories and Terminal Configurations, etc.

**Additional context**
Tool would be used during data modeling exercises with a customer.

**Comment by MikeMillerGIS** [comment]
request by SE

**Comment by jalsup** [comment]
I could see cloning Asset Group, Tier I question.
Copying Asset Groups and Types to other classes, I can see that.
