### ISSUE TITLE
Trace to Trace Configurations tool failing

### ISSUE THREAD

**Issue by jclarke100** [Esri/Utility-Data-Management-Support-Tools#33]
**Describe the bug**
From Pro 3.1.0 I get the error below

_udms 0.3.1.1
Extracted 1 trace calls
Downstream1
Failed to execute. Parameters are not valid.
[ERROR 000732:](javascript:void(0);) Input Utility Network: Dataset in_utility_network="Water Utility Network" does not exist or is not supported
[ERROR 000800:](javascript:void(0);) The value is not a member of Connected | Subnetwork | Subnetwork controllers | Upstream | Downstream | Loops | Shortest path | Isolation.
Failed to execute (AddTraceConfiguration).
Failed script Trace to Trace Configurations..._

**To Reproduce**
1. Download Water Foundation UN solution (v1.2)
2. Open the solution in ArcGIS Pro 3.1
3. Add UDMS toolbox 3.1
4. From Tracing gallery choose Downstream, then pick domain Water Domain, tier Water System. Run trace (succeeds)
5. Right-click Run - Copy Python Command
6. Open Trace to Trace Configurations
7. In the Python text-box, right-click Paste (arcpy command pastes)
8. Fill in name, description and tags text boxes.
9. Click Run - get error.

**Desktop:**
 - OS: Windows 10

**Additional context**
Same steps, work fine for me with UDMS 2.9.1 and Pro 2.9.5. Though note the copy python adds "with arcpy.EnvManager(scratchWorkspace..." which does not occur at 3.1.

**Comment by MikeMillerGIS** [comment]
We pushed a fix for this in both 3.1 and 2.9(the problem would have occurred there if someone happened to pass in named params).  Please let us know if fixes the issue for you, it did in our test.

**Comment by jclarke100** [comment]
Yes  - that fixed it for me. Thanks!
