### ISSUE TITLE
Failed to parse error message for dirty Area

### ISSUE THREAD

**Issue by fayazhussainalibaig** [Esri/Utility-Data-Management-Support-Tools#35]
**Describe the bug**
Summarize Area tool fails as it isn't able to parse dirty area .

![image](https://user-images.githubusercontent.com/4321693/232377243-e21d25ac-a8f9-4d8a-adc6-025462c16523.png)

**Comment by MikeMillerGIS** [comment]
It appears the searchcursor failed to retrieve the dirty areas.  How many dirty areas do you have?  I am also interested in that warning, can you post the attributes that are in the dirty area with the OID of 15530?

**Comment by pLeBlanc93** [comment]
The 400 error is coming from reading feature space. If you use a client-server connection to the UN, does it give a different error?

As for the warnings, I can reproduce locally. The issue appears to be a subnetwork name with a comma.

**Comment by fayazhussainalibaig** [comment]
Hi Paul,

Nope we didn't encounter an error with client-server connection.
Does subnetwork name with comma is an issue for this tool?

Please find the screenshot of the attributes of dirty area you mentioned.
[image: image.png]

**Comment by pLeBlanc93** [comment]
Yes, I've resolved the comma in subnetwork name. Here's a preview release with that fix: https://github.com/Esri/Utility-Data-Management-Support-Tools/blob/2.9.3/UtilityDataManagementSupport.atbx

Still not sure what could cause the 400 error, though.

**Comment by fayazhussainalibaig** [comment]
Thank you Paul. You are a life saver.

**Comment by danielsimo** [comment]
Hi @pLeBlanc93  and @MikeMillerGIS ,

Thanks so much for assisting us with this issue. At this stage, this is a critical issue for us, as we need the report generated by this tool to effect investigate and report back to the client the topology errors that we have been encountering in their DEV/SIT and UAT environments. 

I've downloaded the latest version of the tool (via the link provided by Paul) and have run the tool again. Unfortunately, we still experience the same issue.

Just so you know, we are currently running ArcGIS Pro 2.9.5 and we have a total of 4560 dirty areas.

The below are the screenshots show with the parameters that we used to run the tool and the error messages:

Input Network: UNM Feature Service
![Capture1](https://user-images.githubusercontent.com/48465801/233875007-fa7c810e-168e-44db-9f19-2a5a69945473.PNG)

Input Network: UNM Direct EGDB Connection
![Capture2](https://user-images.githubusercontent.com/48465801/233875089-fd3889b8-c82d-4aff-877d-4d216031df66.PNG)

Could you please assist us? Thank You

Regards
Daniel Simo

**Comment by pLeBlanc93** [comment]
Aha, it is SQL Server. GlobalID are not stored as text, so somehow the tool is passing a malformed GUID in the query. I can reproduce it synthetically.

**Comment by danielsimo** [comment]
@pLeBlanc93 - Thanks so much for your prompt response. I've just sent you a copy of my data via email.

Regards
Dan Simo

**Comment by MikeMillerGIS** [comment]
this is resolved in 2.9.3/3.1.1
