### ISSUE TITLE
Update Data Source tool crashing in Pro 3.1 for Specific map

### ISSUE THREAD

**Issue by jalsup** [Esri/Utility-Data-Management-Support-Tools#36]
**Describe the bug**

**To Reproduce**
1. Open Pro 3.1 Project.  
2. Add tool UtilityDataManagementSupport to Toolboxes
3. Import Map "Electric Network Editor"
4. Execute Tool "Update Data Source" found in Map folder of UtilityDataManagementSupport toolbox.  Can use python below
arcpy.ImportToolbox(r"D:\Projects\ESRI-BZ\BZ_Check.atbx")
arcpy.udms.AdjustDataSources(
    target_workspace=r"D:\Projects\ESRI-BZ\Electric_UtilityNetwork.gdb",
    maps="'Electric Network Editor'",
    update_sr=True
)

**Expected behavior**
Data source of layers to change instead of crashing pro

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 113

**Smartphone (please complete the following information):**

**Additional context**

Data: \\pleblanc\public\FromJohn\Issue36

**Comment by pLeBlanc93** [comment]
It is crashing in Pro 3.2 on `PyArcGISLayerModule::GetFIDSetForSubtypeGroupLayer+0x3d3 [C:\ArcGIS\Geoprocessing\Python\arcgisscripting\PyLayer.cpp @ 241]`
