### ISSUE TITLE
Unable to package toolbox in a ppkx

### ISSUE THREAD

**Issue by ducroix-magis** [Esri/Utility-Data-Management-Support-Tools#43]
**Describe the bug**
When using the "package project" tool to create a ppkx including toolbox, the tool fails with message : 
[ERROR 001238:](javascript:void(0);) Script Batch Trace contains broken project data source: String

**To Reproduce**
- Add UDMS to Project
- Use "Package project" tool in version 3.1 with "include toolboxes" checked

**Expected behavior**
Toolbox is packed in the ppkx

**Screenshots**
![image](https://github.com/Esri/Utility-Data-Management-Support-Tools/assets/98360749/e4e928d4-a363-4c58-93aa-4501663c9795)

**Desktop (please complete the following information):**
 - OS: Windows
 - AGPro 3.1.3
 - UDMS 3.1.2

**Comment by MikeMillerGIS** [comment]
I think there are bugs in 3.1 where the toolbox consolidation was converting atbx.  There might not be anything we can do.  
Here is the result of 3.2
![image](https://github.com/Esri/Utility-Data-Management-Support-Tools/assets/2707285/aeef074f-d752-4d77-85b1-e8e34b00ab15)
