### ISSUE TITLE
Summarize and Report tools returning errors

### ISSUE THREAD

**Issue by areynolds15** [Esri/Utility-Data-Management-Support-Tools#44]
When running the Asset Package Configuration Report and Asset Package Rename Report on the Naperville example Asset Package, I get errors relating to "AttributeError: 'Series' object has no attribute 'iteritems'"

Running on ArcGIS Pro 3.2.1 with the UtilityDataManagementSupport_31.atbx. Database and ArcGIS Pro are in an AWS workspace. 

The Summarize Attribute Rules error is different from the other two tools. Both log files attached. 
[Summarize Attribute Rules_error.txt](https://github.com/Esri/Utility-Data-Management-Support-Tools/files/14142337/Summarize.Attribute.Rules_error.txt)
[Asset Package Configuration Report_error.txt](https://github.com/Esri/Utility-Data-Management-Support-Tools/files/14142338/Asset.Package.Configuration.Report_error.txt)

**Comment by MikeMillerGIS** [comment]
can you post a screen shot of the GP call?

**Comment by areynolds15** [comment]
attached here. 
![GP_SummarizeARs](https://github.com/Esri/Utility-Data-Management-Support-Tools/assets/114671267/02f0d59d-d591-4629-9f99-6f6cdc0e4918)
![GP_configurationReport](https://github.com/Esri/Utility-Data-Management-Support-Tools/assets/114671267/e8053d11-4474-4694-a431-59576925ec68)

**Comment by areynolds15** [comment]
The "Report and Summarize Attribute Rules" does work from that toolbox. 

The Asset Package Configuration Report still failed, new error log attached. 
[Asset Package Configuration Report_3.2_error.txt](https://github.com/Esri/Utility-Data-Management-Support-Tools/files/14212966/Asset.Package.Configuration.Report_3.2_error.txt)

**Comment by MikeMillerGIS** [comment]
I am not able to repo that issue.  Did you chance anything in the config?

![image](https://github.com/Esri/Utility-Data-Management-Support-Tools/assets/2707285/100b7ab9-c0cd-45be-bea6-4848410cd47d)

**Comment by MikeMillerGIS** [comment]
We were able to repo the issue when the asset package configuration table gets removed or renamed.

**Comment by areynolds15** [comment]
oh, ha! That makes sense, sorry. I'm getting an error for the Subnetwork Aggregator as well. I do actually have subnetworks this time. I'm not using any of the parameters except the Input UN and output folder, but it seems like that should be ok, from the metadata. This is on a file gdb UN - Error log attached.
[SubnetworkAggregator_error.txt](https://github.com/Esri/Utility-Data-Management-Support-Tools/files/14223333/SubnetworkAggregator_error.txt)

**Comment by MikeMillerGIS** [comment]
we pushed a fix that added some validation that should resolve your issue - https://github.com/Esri/Utility-Data-Management-Support-Tools/blob/Preview3.1.2/UtilityDataManagementSupport.atbx

can you test it out?

**Comment by MikeMillerGIS** [comment]
I could not repo the SubnetworkAgg error.
![image](https://github.com/Esri/Utility-Data-Management-Support-Tools/assets/2707285/720c8319-2e36-4a6f-b811-21dabcf328f4)

Did you check any other settings?  Was this on the sample water data?
