### ISSUE TITLE
Configure UN layers does nothing

### ISSUE THREAD

**Issue by ducroix-magis** [Esri/Utility-Data-Management-Support-Tools#48]
**Describe the bug**
Hello, after successfully running the "Configure UN Layers" on my APRX's map, nothing appears in the popups

**To Reproduce**
open ArcGIS Pro and use the toolbox from latest (3.3) UDMS
![image](https://github.com/user-attachments/assets/919589c4-7019-4f26-9e38-71d019f8b68b)

Then in ArcGIS Pro, open the map and look at the popups parameter pane or open features' popup pane
![image](https://github.com/user-attachments/assets/3ab8bdea-da20-4624-8234-44bd1bad5373)

**Expected behavior**
Some fields (presumably Arcade fields should appear in the popups.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - ArcGIS Pro 3.3.1
- UDMS 3.3.0

**Comment by MikeMillerGIS** [comment]
If you specify an APRX, it does not touch the current pro project and creates a copy.  Can you see if you have a _1.aprx in that folder?  Leave the APRX blank if you want to affect the current map.

**Comment by ducroix-magis** [comment]
Yes, I have a new tigre_dev0.aprx with the newly populated popups.
Also, leaving the aprx blank works well for the current aprx's maps.
Thank you
