### ISSUE TITLE
value -2 add to export matrix

### ISSUE THREAD

**Issue by ducroix-magis** [Esri/Utility-Data-Management-Support-Tools#7]
**Describe the bug**
When using the Export matrix toolbox, I see values 1 but also of -2 in the workbook.
Maybe due to rules duplicates in the database ?

**To Reproduce**
1. Export matrix

**Expected behavior**
Only values of 1 in the proper cells

**Screenshots**
![image](https://user-images.githubusercontent.com/98360749/150874875-4888fcde-c444-4684-adf4-611a5dea980d.png)

![image](https://user-images.githubusercontent.com/98360749/150874918-c81f855a-0389-449d-8a1c-3a9767d43dd5.png)

**Additional context**
I started with an existing asset package, then used d_configuration to remove several subtypes (but not explicitly removed rules).
Then after I applied the asset package in a mobile geodatabase, I added several non-existing rules and maybe creates duplicates.

**Comment by pLeBlanc93** [comment]
-2 (and black fill) means that a rule between these is invalid.

A future release will have an introduction worksheet that explains the values, colors, etc.

**Comment by ducroix-magis** [comment]
Thank you, Paul, for the quick response,
By 'invalid', you mean that it is not permitted by the data model, or that it is incorrect and should be modified ?
Is there a way to correct these rules ?

**Comment by pLeBlanc93** [comment]
It's not permitted by the UN information model.

Looking at containment, everything not in green would be filled with a -2 because it is never permissible.

https://pro.arcgis.com/en/pro-app/latest/help/data/utility-network/feature-restrictions.htm#ESRI_SECTION1_2554BD1EA4B346A89F76C640E441ED0D
